// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_VW_PARSER_H_
#define FLATBUFFERS_GENERATED_SCHEMA_VW_PARSER_H_

#include "flatbuffers/flatbuffers.h"

namespace VW {
namespace parser {

struct MyTable;
struct MyTableBuilder;

struct MyTable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MyTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_A_NAME = 4,
    VT_A_VALUE = 6,
    VT_A_FLAG = 8
  };
  const flatbuffers::String *a_name() const {
    return GetPointer<const flatbuffers::String *>(VT_A_NAME);
  }
  float a_value() const {
    return GetField<float>(VT_A_VALUE, 0.0f);
  }
  bool a_flag() const {
    return GetField<uint8_t>(VT_A_FLAG, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_A_NAME) &&
           verifier.VerifyString(a_name()) &&
           VerifyField<float>(verifier, VT_A_VALUE, 4) &&
           VerifyField<uint8_t>(verifier, VT_A_FLAG, 1) &&
           verifier.EndTable();
  }
};

struct MyTableBuilder {
  typedef MyTable Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_a_name(flatbuffers::Offset<flatbuffers::String> a_name) {
    fbb_.AddOffset(MyTable::VT_A_NAME, a_name);
  }
  void add_a_value(float a_value) {
    fbb_.AddElement<float>(MyTable::VT_A_VALUE, a_value, 0.0f);
  }
  void add_a_flag(bool a_flag) {
    fbb_.AddElement<uint8_t>(MyTable::VT_A_FLAG, static_cast<uint8_t>(a_flag), 0);
  }
  explicit MyTableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MyTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MyTable>(end);
    return o;
  }
};

inline flatbuffers::Offset<MyTable> CreateMyTable(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> a_name = 0,
    float a_value = 0.0f,
    bool a_flag = false) {
  MyTableBuilder builder_(_fbb);
  builder_.add_a_value(a_value);
  builder_.add_a_name(a_name);
  builder_.add_a_flag(a_flag);
  return builder_.Finish();
}

inline flatbuffers::Offset<MyTable> CreateMyTableDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *a_name = nullptr,
    float a_value = 0.0f,
    bool a_flag = false) {
  auto a_name__ = a_name ? _fbb.CreateString(a_name) : 0;
  return VW::parser::CreateMyTable(
      _fbb,
      a_name__,
      a_value,
      a_flag);
}

inline const VW::parser::MyTable *GetMyTable(const void *buf) {
  return flatbuffers::GetRoot<VW::parser::MyTable>(buf);
}

inline const VW::parser::MyTable *GetSizePrefixedMyTable(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<VW::parser::MyTable>(buf);
}

inline bool VerifyMyTableBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VW::parser::MyTable>(nullptr);
}

inline bool VerifySizePrefixedMyTableBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VW::parser::MyTable>(nullptr);
}

inline void FinishMyTableBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VW::parser::MyTable> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMyTableBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VW::parser::MyTable> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace parser
}  // namespace VW

#endif  // FLATBUFFERS_GENERATED_SCHEMA_VW_PARSER_H_
